### PR TITLE
Update docstrings for Plan interface

### PR DESCRIPTION
**Pull request by janden**
And some other stuff.

### CODE REVIEW

**Comment by ahbarnett** [comment]
looks good - thanks.

**Comment by ahbarnett** [comment]
Ah, this has broken something: I'm not sure the simple interfaces got updated to match the new Plan ordering? Anyway, here goes:

```python3 python/test/run_accuracy_tests.py
Accuracy and speed tests for 100000 nonuniform points and eps=1e-06 (error estimates use 5 samples per run)
Traceback (most recent call last):
  File "python/test/run_accuracy_tests.py", line 3, in <module>
    accuracy_speed_tests(100000,100000,1e-6)
  File "/home/alex/numerics/finufft/python/test/accuracy_speed_tests.py", line 45, in accuracy_speed_tests
    ret=finufft.nufft1d1(xj,cj,ms,fk,eps,iflag)
  File "/home/alex/miniconda3/envs/idp/lib/python3.7/site-packages/finufft/_interfaces.py", line 750, in nufft1d1
    return invoke_guru(1,1,x,None,None,c,None,None,None,out,isign,eps,n_modes,**kwargs)
  File "/home/alex/miniconda3/envs/idp/lib/python3.7/site-packages/finufft/_interfaces.py", line 599, in invoke_guru
    plan = Plan(tp,n_modes,eps,isign,n_trans,**dict(kwargs,dtype=pdtype))
  File "/home/alex/miniconda3/envs/idp/lib/python3.7/site-packages/finufft/_interfaces.py", line 90, in __init__
    if iflag==None:
UnboundLocalError: local variable 'iflag' referenced before assignment
Exception ignored in: <function Plan.__del__ at 0x7f4bc4c52170>
Traceback (most recent call last):
  File "/home/alex/miniconda3/envs/idp/lib/python3.7/site-packages/finufft/_interfaces.py", line 319, in __del__
    destroy(self.inner_plan)
AttributeError: 'Plan' object has no attribute 'inner_plan'
makefile:330: recipe for target 'python' failed
make: *** [python] Error 1
```

**Comment by janden** [comment]
Ah sorry about that. I changed the order of n_trans and forgot to update it where it's called (I only looked through the examples, which call it using kwargs, so order doesn't matter there). Will fix.

**Comment by janden** [comment]
Nm looks like @lu1and10 fixed this already. Thank you1

**Pull request merged**
