### PR TITLE
Add templated docstrings for Python

### LINKED ISSUE #120: py docstrings

### PR DESCRIPTION
**Pull request by janden**
It's not the prettiest, but it does the trick and should be fairly easy to maintain.

Fixes #120.

### CODE REVIEW

**Comment by ahbarnett** [comment]
Cool. I hope you found this as entertaining as I did for the matlab and C++ ones :)    I haven't understood how f.__doc__ inserts it as the docstring, but it's cool it can all remain in python (not the bash I has to use). I'm pulling in before trying it out.

**Comment by ahbarnett** [comment]
Hmm - this sucks but running ``cd docs; make html`` to do sphinx (v 1.3.6) build locally doesn't update the html (it's still the old docs). I even tried ``make python`` to build the pkg first. So I can't appreciate the beautiful docstrings you have auto-built. Maybe Libin has more success?

**Comment by janden** [comment]
> how f.doc inserts it as the docstring

So basically adding the docstring as a string right after the function signature assigns it to `f.__doc__`, but a function is an object (run `dir(f)` to find out what's in there), so you can modify it and its attributes after the fact (you can imagine that there's great potential for headache here).

> running `cd docs; make html` to do sphinx (v 1.3.6) build locally doesn't update the html (it's still the old docs)

Yeah I had the same problem. Part of the issue is that Sphinx only knows about the packages that are in PYTHONPATH. Since you already have one installed (from a previous run of `make python`), that one will be the one that's found when Sphinx runs `import finufftpy`. Normally, another run of `make python` should work, but it didn't for me either. What ended up working for me was to run `pip install` myself:

```
(cd python && pip install .) && (cd docs && make html)
```

Ideally, all of this should be circumvented by having pip install “in place” with `pip install -e .`, but this gives weird crashes for me. An in place installation will basically just symlink the source code into the PYTHONPATH, which means that when you update the code, that update is reflected when someone types `import finufftpy`.

**Comment by janden** [comment]
And yes, it was quite entertaining. I was thinking about how to template some simple examples this morning. Should be fairly doable.

**Comment by lu1and10** [comment]
Glad it works for you now, I'm not sure when texext, latexmk were installed
on my Mac so that the sphinx-build works with python docs for me.
I will take care the python guru interface docstrings follow your matlab
guru ones.

**Comment by janden** [comment]
Yeah there are quite a few installation issues for Python that we need to deal with. Part of this will be easier once we drop the pybind11 dependency.

I had started on the Plan docstrings but haven't had time to finish them yet. (Was planning on finishing tonight.) Did you already write the docstrings, @lu1and10?

**Comment by lu1and10** [comment]
I have not started yet. I committed the change for renaming python
package from finufftpy to finufft, also changed the python docs/test for
this renaming.

**Pull request merged**
