### PR TITLE
Cleanup setup.py

### PR DESCRIPTION
**Pull request by janden**
Lots of old code there that is no longer needed. Also removed `requirements.txt` since the dependencies are already listed in `setup.py`. Finally add a check to make sure `libfinufft.so` is loadable from `ctypes` before proceeding with install.

### CODE REVIEW

**Comment by ahbarnett** [comment]
Thanks!

is this in response to my #145  - and does it fix it?

Problem is I just referred to requirements.txt in the install docs! (it's useful for setting up a virtualenv).
Is it terrible to duplicate it?

To check: python-dotenv is not needed now, right, since there is no need to read CXX in from make.inc to specify compiler (on OSX, etc).  Correct?

**Comment by ahbarnett** [comment]
bringing in anyway since I like it. I may re-add req.txt.

**Comment by ahbarnett** [comment]
ack - on my i7/ubuntu/py3.7:
```
    OSError: libfinufft.so: cannot open shared object file: No such file or directory
```

**Comment by janden** [comment]
Take it easy… That's why we have PRs, so we can discuss and test before we merge.

> is this in response to my #145 - and does it fix it?

No I can do a separate one for that.

> Problem is I just referred to requirements.txt in the install docs! (it's useful for setting up a virtualenv).
> Is it terrible to duplicate it?

Ah ok. I can add it back in. There's a way to have `setup.py` read it in and parse it.

> To check: python-dotenv is not needed now, right, since there is no need to read CXX in from make.inc to specify compiler (on OSX, etc). Correct?

Correct.

> Your initial try doesn't find them, and that makes it crash out?

What command brings up that error?

**Comment by ahbarnett** [comment]
Yeah, I should have tested a separate branch.

Can't we replace
	(export FINUFFT_DIR=$(shell pwd); cd python; $(PYTHON) -m pip -v install .)
by
	(export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(shell pwd)/lib; cd python; $(PYTHON) -m pip -v install .)

or something like that, since FINUFFT_DIR only has the purpose of finding the lib.so!
Do you want to zoom right now?

**Comment by ahbarnett** [comment]
Error is a simply doing make clean python

**Comment by janden** [comment]
Send you a zoom link.

**Pull request merged**
