### PR TITLE
Update cufinufft docker images

### PR DESCRIPTION
**Pull request by janden**
This PR gives the cufinufft docker images a bit of an update. In particular:
– A docker file for CUDA 12 is added (based on manylinux2014).
– A small test script (`tools/cufinufft/test.sh`) is added. At some point, this can be the basis of the Jenkins CI tests.
– The wheel-building script (`tools/cufinufft/build-wheels.sh') is cleaned-up a bit.
– Files are copied into the docker image in a staggered way, preventing the cache from getting invalidated unnecessarily (such as when the Python code or docs are modified, but the C++ code stays the same).
– The dependencies in the docker images are reduced to a minimum in order to build and test the library. This speeds up image building and reduces its footprint.
– The CUDA 10 docker image is removed.

### CODE REVIEW

**Comment by ahbarnett** [comment]
THanks for maintinaing this. Now, sorry for a basic question: is docker used to build the pypi binary for cufinufft? Maybe it would be worth adding a bullet in `docs/devnotes.rst` about how this works and what "wheels" means? (if this is the same?).   Thanks! Alex

**Comment by janden** [comment]
> Now, sorry for a basic question: is docker used to build the pypi binary for cufinufft? 

That's correct. There are some commands in `tools/cufinufft/distribution_helper.sh` that do this.


> Maybe it would be worth adding a bullet in `docs/devnotes.rst` about how this works and what "wheels" means? (if this is the same?).

Good point. I will do this.

**Comment by blackwer** [comment]
Ah I was gonna review this and was too late. By layering finufft installs inside the docker image, you create a lot of cache layers on the CI machines. finufft is small, but it's probably better practice to move the pull/build/etc step into the jenkinsfile where it's done at runtime, rather than ending up with a new docker image for every CI request.

**Comment by janden** [comment]
> By layering finufft installs inside the docker image, you create a lot of cache layers on the CI machines. finufft is small, but it's probably better practice to move the pull/build/etc step into the jenkinsfile where it's done at runtime, rather than ending up with a new docker image for every CI request.

Right that makes a lot of sense. This is how it was structured before, but I can see how it could create problems. Will make an issue.

**Pull request merged**
