### PR TITLE
fix onedim_fseries_kernel to give threading independent results

### LINKED ISSUE #363: Different result when transforming stack vs singleton
Using the python interface on Linux, I find that I'm getting different results when I transform a volume stack compared to transforming the volumes of the stack individually. I only see this behavior when using single precision.

I've tested this out on the latest stable release as well as a build from master. Here is a test script I'm using:

```
import finufft                                                                                                            
import numpy as np                                                                                                        
                                                                                                                          
singles = np.float32, np.complex64                                                                                        
doubles = np.float64, np.complex128                                                                                       
                                                                                                                          
                                                                                                                          
def run_finufft(dtypes):                                                                                                  
    # Generate a stack of volumes.                                                                                        
    dtype, complex_dtype = dtypes                                                                                         
    res = 23                                                                                                              
    N = 3  # number of volumes                                                                                            
    vols = np.arange(1, 1 + N * res**3, dtype=dtype).reshape(N, res, res, res)                                            
    # np.random.seed(1)                                                                                                   
    # vols = np.random.randn(N, res, res, res)                                                                            
    vols = np.array(vols, copy=False, dtype=complex_dtype, order="C")                                                     
                                                                                                                          
    # Generate set of fourier grid points.                                                                                
    pts_1d = np.linspace(-np.pi, np.pi, res, dtype=dtype)                                                                 
    x, y, z = np.meshgrid(pts_1d, pts_1d, pts_1d)                                                                         
    fourier_pts = np.vstack([x.flatten(), y.flatten(), z.flatten()])                                                      
                                                                                                                          
    # Make finufft plan for stack of volumes.                                                                             
    eps = 1e-8                                                                                                            
    if np.finfo(dtype).eps > eps:                                                                                         
        eps = np.finfo(dtype).eps                                                                                         
    transform_plan = finufft.Plan(                                                                                        
        nufft_type=2, n_modes_or_dim=(res,) * 3, eps=eps, n_trans=3, dtype=dtype                                          
    )                                                                                                                     
    transform_plan.setpts(*fourier_pts)                                                                                   
                                                                                                                          
    # Execute transform on volume stack.                                                                                  
    f_vols = transform_plan.execute(vols)                                                                                 
    f_vols = f_vols.reshape(-1, res, res, res)                                                                            
                                                                                                                          
    # Make finufft plan for single volumes.                                                                               
    transform_plan = finufft.Plan(                                                                                        
        nufft_type=2, n_modes_or_dim=(res,) * 3, eps=eps, n_trans=1, dtype=dtype                                          
    )                                                                                                                     
    transform_plan.setpts(*fourier_pts)                                                                                   
                                                                                                                          
    # Execute transform on single volumes.                                                                                
    f_vol_0 = transform_plan.execute(vols[0]).reshape(res, res, res)                                                      
    f_vol_1 = transform_plan.execute(vols[1]).reshape(res, res, res)                                                      
    f_vol_2 = transform_plan.execute(                                                                                     
        vols[2],                                                                                                          
    ).reshape(res, res, res)                                                                                              
                                                                                                                          
    # Test that we get the same transforms with stack and singletons.                                                     
    print(dtypes)                                                                                                         
    print(                                                                                                                
        f"allclose: {np.allclose(f_vols[0], f_vol_0)}, ",                                                                 
        f"max_abs_diff: {np.max(abs(f_vols[0] - f_vol_0))}, ",                                                            
        f"rmse: {np.sqrt(np.mean(abs(f_vols[0] - f_vol_0)**2))}",                                                         
    )                                                                                                                     
    print(                                                                                                                
        f"allclose: {np.allclose(f_vols[1], f_vol_1)}, ",                                                                 
        f"max_abs_diff: {np.max(abs(f_vols[1] - f_vol_1))}, ",                                                            
        f"rmse: {np.sqrt(np.mean(abs(f_vols[1] - f_vol_1)**2))}",                                                         
    )                                                                                                                     
    print(                                                                                                                
        f"allclose: {np.allclose(f_vols[2], f_vol_2)}, ",                                                                 
        f"max_abs_diff: {np.max(abs(f_vols[2] - f_vol_2))}, ",                                                            
        f"rmse: {np.sqrt(np.mean(abs(f_vols[2] - f_vol_2)**2))}",                                                         
    )                                                                                                                     
                                                                                                                          
                                                                                                                          
run_finufft(doubles)                                                                                                      
run_finufft(singles)        
``` 

Below is the output of the script. The stack is `allclose` to singletons in double precision, but we're pretty far off in singles.
```
(<class 'numpy.float64'>, <class 'numpy.complex128'>)
allclose: True,  max_abs_diff: 5.587935447692871e-09,  rmse: 1.3931081848390707e-10
allclose: True,  max_abs_diff: 7.4744308697948e-09,  rmse: 3.2122794922856015e-10
allclose: True,  max_abs_diff: 1.626484952547865e-08,  rmse: 4.898117388072168e-10
(<class 'numpy.float32'>, <class 'numpy.complex64'>)
allclose: False,  max_abs_diff: 2.0,  rmse: 0.055754758417606354
allclose: False,  max_abs_diff: 16.03447914123535,  rmse: 0.21659733355045319
allclose: False,  max_abs_diff: 8.000244140625,  rmse: 0.24948608875274658
```

Admittedly, the volume is a little contrived but I get the failure on a random volume (commented out in the script) as well.

### PR DESCRIPTION
**Pull request by blackwer**
@lu1and10 @ahbarnett 
The prior implementation gave different work sizes for different threads and then updated the phase factor by multiplying coefficients rather than using the power function.

Unfortunately: `pow(x, y) * x != pow(x, y + 1)`

This simplifies the routine to just use the power function and let openmp evenly divide the work rather than chunking ourselves - ultimately making the results thread independent

closes #363

driver/test code:
```python
import finufft
import numpy as np
from threadpoolctl import threadpool_limits

singles = np.float32, np.complex64
doubles = np.float64, np.complex128


def run_finufft(dtypes, res, nthr):
    # Generate a stack of volumes.
    dtype, complex_dtype = dtypes
    N = 3  # number of volumes
    vols = np.arange(1, 1 + N * res**3, dtype=complex_dtype).reshape(N, res, res, res)

    # Generate set of fourier grid points.
    pts_1d = np.linspace(-np.pi, np.pi, res, dtype=dtype)
    x, y, z = np.meshgrid(pts_1d, pts_1d, pts_1d)
    fourier_pts = np.vstack([x.flatten(), y.flatten(), z.flatten()])

    # Make finufft plan for stack of volumes.
    eps = 1e-8
    if np.finfo(dtype).eps > eps:
        eps = np.finfo(dtype).eps
    with threadpool_limits(limits=nthr, user_api='openmp'):
        transform_plan = finufft.Plan(
            nufft_type=2, n_modes_or_dim=(res,) * 3, eps=eps, n_trans=3, dtype=dtype, debug=0, maxbatchsize=8
        )
        transform_plan.setpts(*fourier_pts)

        # Execute transform on volume stack.
        f_vols = transform_plan.execute(vols).reshape(-1, res, res, res)


    # Make finufft plan for single volumes.
    with threadpool_limits(limits=1, user_api='openmp'):
        transform_plan = finufft.Plan(
            nufft_type=2, n_modes_or_dim=(res,) * 3, eps=eps, n_trans=1, dtype=dtype, 
        )
        transform_plan.setpts(*fourier_pts)

        # Execute transform on single volumes.
        f_vol_0 = transform_plan.execute(vols[0]).reshape(res, res, res)
        f_vol_1 = transform_plan.execute(vols[1]).reshape(res, res, res)
        f_vol_2 = transform_plan.execute(vols[2]).reshape(res, res, res)

    # Test that we get the same transforms with stack and singletons.
    relerr = np.max([np.max(np.abs(((f_vol_0 - f_vols[0]) / f_vol_0))),
                     np.max(np.abs(((f_vol_1 - f_vols[1]) / f_vol_0))),
                     np.max(np.abs(((f_vol_2 - f_vols[2]) / f_vol_0))),
                     ])
    max_abs_diff = np.max([
        np.abs(f_vols[0] - f_vol_0),
        np.abs(f_vols[1] - f_vol_1),
        np.abs(f_vols[2] - f_vol_2),
    ])
    return (relerr, max_abs_diff)

for nthr in range(1, 32):
    res = 23
    print(nthr, run_finufft(singles, res, nthr))
```

output:
```
1 (0.0, 0.0)
2 (0.0, 0.0)
3 (0.0, 0.0)
4 (0.0, 0.0)
5 (0.0, 0.0)
6 (0.0, 0.0)
7 (0.0, 0.0)
8 (0.0, 0.0)
9 (0.0, 0.0)
10 (0.0, 0.0)
11 (0.0, 0.0)
12 (0.0, 0.0)
13 (0.0, 0.0)
14 (0.0, 0.0)
15 (0.0, 0.0)
16 (0.0, 0.0)
17 (0.0, 0.0)
18 (0.0, 0.0)
19 (0.0, 0.0)
20 (0.0, 0.0)
21 (0.0, 0.0)
22 (0.0, 0.0)
23 (0.0, 0.0)
24 (0.0, 0.0)
25 (0.0, 0.0)
26 (0.0, 0.0)
27 (0.0, 0.0)
28 (0.0, 0.0)
29 (0.0, 0.0)
30 (0.0, 0.0)
31 (0.0, 0.0)
```

### CODE REVIEW

**Comment by lu1and10** [comment]
> @lu1and10 @ahbarnett The prior implementation gave different work sizes for different threads and then updated the phase factor by multiplying coefficients rather than using the power function.
> 
> Unfortunately: `pow(x, y) * x != pow(x, y + 1)`
> 
> This simplifies the routine to just use the power function and let openmp evenly divide the work rather than chunking ourselves - ultimately making the results thread independent
> 
> closes #363
> 
> driver/test code:
> 
> ```python
> import finufft
> import numpy as np
> from threadpoolctl import threadpool_limits
> 
> singles = np.float32, np.complex64
> doubles = np.float64, np.complex128
> 
> 
> def run_finufft(dtypes, res, nthr):
>     # Generate a stack of volumes.
>     dtype, complex_dtype = dtypes
>     N = 3  # number of volumes
>     vols = np.arange(1, 1 + N * res**3, dtype=complex_dtype).reshape(N, res, res, res)
> 
>     # Generate set of fourier grid points.
>     pts_1d = np.linspace(-np.pi, np.pi, res, dtype=dtype)
>     x, y, z = np.meshgrid(pts_1d, pts_1d, pts_1d)
>     fourier_pts = np.vstack([x.flatten(), y.flatten(), z.flatten()])
> 
>     # Make finufft plan for stack of volumes.
>     eps = 1e-8
>     if np.finfo(dtype).eps > eps:
>         eps = np.finfo(dtype).eps
>     with threadpool_limits(limits=nthr, user_api='openmp'):
>         transform_plan = finufft.Plan(
>             nufft_type=2, n_modes_or_dim=(res,) * 3, eps=eps, n_trans=3, dtype=dtype, debug=0, maxbatchsize=8
>         )
>         transform_plan.setpts(*fourier_pts)
> 
>         # Execute transform on volume stack.
>         f_vols = transform_plan.execute(vols).reshape(-1, res, res, res)
> 
> 
>     # Make finufft plan for single volumes.
>     with threadpool_limits(limits=1, user_api='openmp'):
>         transform_plan = finufft.Plan(
>             nufft_type=2, n_modes_or_dim=(res,) * 3, eps=eps, n_trans=1, dtype=dtype, 
>         )
>         transform_plan.setpts(*fourier_pts)
> 
>         # Execute transform on single volumes.
>         f_vol_0 = transform_plan.execute(vols[0]).reshape(res, res, res)
>         f_vol_1 = transform_plan.execute(vols[1]).reshape(res, res, res)
>         f_vol_2 = transform_plan.execute(vols[2]).reshape(res, res, res)
> 
>     # Test that we get the same transforms with stack and singletons.
>     relerr = np.max([np.max(np.abs(((f_vol_0 - f_vols[0]) / f_vol_0))),
>                      np.max(np.abs(((f_vol_1 - f_vols[1]) / f_vol_0))),
>                      np.max(np.abs(((f_vol_2 - f_vols[2]) / f_vol_0))),
>                      ])
>     max_abs_diff = np.max([
>         np.abs(f_vols[0] - f_vol_0),
>         np.abs(f_vols[1] - f_vol_1),
>         np.abs(f_vols[2] - f_vol_2),
>     ])
>     return (relerr, max_abs_diff)
> 
> for nthr in range(1, 32):
>     res = 23
>     print(nthr, run_finufft(singles, res, nthr))
> ```
> 
> output:
> 
> ```
> 1 (0.0, 0.0)
> 2 (0.0, 0.0)
> 3 (0.0, 0.0)
> 4 (0.0, 0.0)
> 5 (0.0, 0.0)
> 6 (0.0, 0.0)
> 7 (0.0, 0.0)
> 8 (0.0, 0.0)
> 9 (0.0, 0.0)
> 10 (0.0, 0.0)
> 11 (0.0, 0.0)
> 12 (0.0, 0.0)
> 13 (0.0, 0.0)
> 14 (0.0, 0.0)
> 15 (0.0, 0.0)
> 16 (0.0, 0.0)
> 17 (0.0, 0.0)
> 18 (0.0, 0.0)
> 19 (0.0, 0.0)
> 20 (0.0, 0.0)
> 21 (0.0, 0.0)
> 22 (0.0, 0.0)
> 23 (0.0, 0.0)
> 24 (0.0, 0.0)
> 25 (0.0, 0.0)
> 26 (0.0, 0.0)
> 27 (0.0, 0.0)
> 28 (0.0, 0.0)
> 29 (0.0, 0.0)
> 30 (0.0, 0.0)
> 31 (0.0, 0.0)
> ```

Great, thanks! I'll test on my side locally.

**Review by ahbarnett — COMMENTED** [review]
Hi Robert,
Interesting simplification.
So, for reasons I discuss in the comments for this routine, it has to be fast, and I recall `pow` being too slow directly (and a complex `pow` should be replaced by real `sin` and `cos` in this case). Hence the phase-winding (which only uses multiply and add), and omp. Could you verify that this PR doesn't slow down this step enough to impact the overall 1D transform speed?

I suggest running
```
test/finufft1d_test 1e7 1e5 1e-12 2 | grep fser
```
both 1-thread and many-threads, and comparing the timings for master vs this PR.

Also, I had not realized thread-independent answers (to machine-precision) were a need for the library? We advertize merely accuracy at the tol level.

Maybe we should discuss...

**Comment by blackwer** [comment]
> I suggest running
> 
> ```
> test/finufft1d_test 1e7 1e5 1e-12 2 | grep fser
> ```

ahhh that's where that is. yeah it's real bad. The net impact over a whole run was in the noise, but this is bad enough that I'll fix it or we can trash this consistency alltogether

> Also, I had not realized thread-independent answers (to machine-precision) were a need for the library? We advertize merely accuracy at the tol level.

It's not, but it's a nice feature and if we only have to fix one routine, it's worth it, imho. This took a lot of research that would have otherwise been unnecessary.

**Comment by lu1and10** [comment]
> Hi Robert, Interesting simplification. So, for reasons I discuss in the comments for this routine, it has to be fast, and I recall `pow` being too slow directly (and a complex `pow` should be replaced by real `sin` and `cos` in this case). Hence the phase-winding (which only uses multiply and add), and omp. Could you verify that this PR doesn't slow down this step enough to impact the overall 1D transform speed?
> 
> I suggest running
> 
> ```
> test/finufft1d_test 1e7 1e5 1e-12 2 | grep fser
> ```
> 
> both 1-thread and many-threads, and comparing the timings for master vs this PR.
> 
> Also, I had not realized thread-independent answers (to machine-precision) were a need for the library? We advertize merely accuracy at the tol level.
> 
> Maybe we should discuss...

I think Alex is correct. C math lib pow seems to be slow. Coincidentally I just see Zorin's group slack discussing using pow for small integer powers  is very expensive relative to multiplications, one may need a customized pow for interger. 

pow(double, int) probably just casts second argument to double. assembly calling pow(double, int) does cast to double then jumps to pow(double, double) 
```
        cvtsi2sd        xmm1, edi
        jmp     pow@PLT
```

**Comment by ahbarnett** [comment]
It's really cos() that would need to be done, basically as in the
onedim_nuft_...
But the phase-winding is much faster on all CPUs+compilers. It remains
to check that phase-winding only perturbs the answers at close to
eps_mach level, as I had assumed and tested long ago.

On Tue, Oct 24, 2023 at 5:46 PM Libin Lu ***@***.***> wrote:
>
> Hi Robert, Interesting simplification. So, for reasons I discuss in the comments for this routine, it has to be fast, and I recall pow being too slow directly (and a complex pow should be replaced by real sin and cos in this case). Hence the phase-winding (which only uses multiply and add), and omp. Could you verify that this PR doesn't slow down this step enough to impact the overall 1D transform speed?
>
> I suggest running
>
> test/finufft1d_test 1e7 1e5 1e-12 2 | grep fser
>
> both 1-thread and many-threads, and comparing the timings for master vs this PR.
>
> Also, I had not realized thread-independent answers (to machine-precision) were a need for the library? We advertize merely accuracy at the tol level.
>
> Maybe we should discuss...
>
> I think Alex is correct. C math lib pow seems to be slow. Coincidentally I just see Zorin's group slack discussing using pow for small integer powers is very expensive relative to multiplications, one may need a customized pow for interger.
>
> pow(double, int) probably just casts second argument to double. assembly calling pow(double, int) does cast to double then jumps to pow(double, double)
>
>         cvtsi2sd        xmm1, edi
>         jmp     ***@***.***
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>



-- 
*-------------------------------------------------------------------~^`^~._.~'
|\  Alex Barnett    Center for Computational Mathematics, Flatiron Institute
| \                 http://users.flatironinstitute.org/~ahb     646-876-5942

**Comment by lu1and10** [comment]
> > I suggest running
> > ```
> > test/finufft1d_test 1e7 1e5 1e-12 2 | grep fser
> > ```
> 
> ahhh that's where that is. yeah it's real bad. The net impact over a whole run was in the noise, but this is bad enough that I'll fix it or we can trash this consistency alltogether
> 
> > Also, I had not realized thread-independent answers (to machine-precision) were a need for the library? We advertize merely accuracy at the tol level.
> 
> It's not, but it's a nice feature and if we only have to fix one routine, it's worth it, imho. This took a lot of research that would have otherwise been unnecessary.

@blackwer it seems the dominate difference between  different threads are coming from fftw.
I don't know what `threadpoolctl` controls in python. Maybe I'm doing something wrong, if I just run @j-c-c 's original python script in issue #363 with the following shell script changing env `OMP_NUM_THREADS`, I still see the difference cross different threads. Tested only fftw, I do get single/doubel tol difference as @blackwer mentioned.
```
#!/bin/bash

for i in {1..128}
do
    echo $i
    export OMP_NUM_THREADS=$i; python jcc_test.py
done

```

**Comment by lu1and10** [comment]
> It's really cos() that would need to be done, basically as in the onedim_nuft_... But the phase-winding is much faster on all CPUs+compilers. It remains to check that phase-winding only perturbs the answers at close to eps_mach level, as I had assumed and tested long ago.
> […](#)
> On Tue, Oct 24, 2023 at 5:46 PM Libin Lu ***@***.***> wrote: Hi Robert, Interesting simplification. So, for reasons I discuss in the comments for this routine, it has to be fast, and I recall pow being too slow directly (and a complex pow should be replaced by real sin and cos in this case). Hence the phase-winding (which only uses multiply and add), and omp. Could you verify that this PR doesn't slow down this step enough to impact the overall 1D transform speed? I suggest running test/finufft1d_test 1e7 1e5 1e-12 2 | grep fser both 1-thread and many-threads, and comparing the timings for master vs this PR. Also, I had not realized thread-independent answers (to machine-precision) were a need for the library? We advertize merely accuracy at the tol level. Maybe we should discuss... I think Alex is correct. C math lib pow seems to be slow. Coincidentally I just see Zorin's group slack discussing using pow for small integer powers is very expensive relative to multiplications, one may need a customized pow for interger. pow(double, int) probably just casts second argument to double. assembly calling pow(double, int) does cast to double then jumps to pow(double, double) cvtsi2sd xmm1, edi jmp ***@***.*** — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>
> -- *-------------------------------------------------------------------~^`^~._.~' |\ Alex Barnett Center for Computational Mathematics, Flatiron Institute | \ http://users.flatironinstitute.org/~ahb 646-876-5942

Yes. Maybe I'm wrong but I'm still see fftw perturbs more than phase-winding does cross different number of threads...

**Comment by blackwer** [comment]
> I don't know what threadpoolctl controls in python.

`threadpoolctl` lets you set the number of `openmp` or `blas` threads dynamically within the context. The reason I thought this was resolved is that...

1. finufft always uses the number of threads for `fftw` that it sees on the first `makeplan` call, so this trick of doing everything in one process is actually telling `finufft` to use one thread the entire time. This is **definitely** not what i wanted with my test script. If i control for that, i see the same issue again, though less so. Now it's only `fftw` generating the different results, and not a combination
2. I actually wrote a simple `fftw` test program where I'm unable to ever get different results depending on the number of simultaneous transforms or threads - so I didn't see how `finufft` was able to pull it off. I'm going to investigate this further for my own personal interest.

Given my discussion with @ahbarnett yesterday about library guarantees, the performance of the `onedim_fseries` routine, and that `fftw` is out of our control, I'm going to close this PR and propose we mark the original issue #363 as `wontfix` since we only make promises about the tolerance, not the consistency. For testing purposes users should just fix the number of threads used by the routine. If `fftw` turns out to be tameable then maybe we could revisit later.

**Comment by blackwer** [comment]
> pow(double, int) probably just casts second argument to double. assembly calling pow(double, int) does cast to double then jumps to pow(double, double)

I've investigated this a bit in my https://github.com/flatironinstitute/sf_benchmarks repo. There are much better options for doing this - notably hardware vector cosine instructions. I'm going to look into this for type 3

**Pull request closed without merging**
