### PR TITLE
Merge in cufinufft to main [WIP]

### PR DESCRIPTION
**Pull request by blackwer**
[cufinufft](https://github.com/flatironinstitute/cufinufft) is a mature port of `finufft` to work with the `cuda` programming model. Given that the main developers have largely moved on to other projects, I thought it would be good to merge the two codebases and slowly integrate the `cuda` port into the main-line.

I used @wendazhou's `cmake` PR as a jumping off point and merged in the `cufinufft` tree into a subfolder, conveniently named `cufinufft`. This was chosen over subprojecting to simplify future development efforts. I chose to keep the history so that work would properly be credited and `git blame` would work as intended, instead of entirely blaming me for literally everything.

~While merging the two codebases to use a common core/API is a significant undertaking, having them both build and install together should be relatively simple. As of the initial commit in this PR, the build systems and code are completely independent. There is nothing connecting them at all. So...~

- [x] Merge source trees
- [x] Integrate build systems of `finufft` and `cufinufft` using the cmake ecosystem (`Makefile` should not be supported for `cufinufft`, imho)
- [x] Move source/tests properly into `finufft` project structure
- [x] Verify correctness
- [x] Fix documentation
- [x] Fix/resolve pip installs
- [ ] ~Add install targets?~ (Delaying for discussions)
- [x] Merge SPREAD_OPTS structs?
- [x] Update CI to do `cufinufft` tests as well
- [ ] ~Change naming conventions and style of `cufinufft` to match `finufft` where possible~ (Once merged)
- [ ] ~Identify redundant code between two projects and unify them~ (Not much. Wait until API unification)
- [ ] ~Identify PRs from `cufinufft` to merge in~ (Once merged)
- [ ] ~Remove any `nvidia` source~
- [x] Add cuda tests to ctests (at least for smoke test)
- [ ] ~Fix version mismatch~ (keeping separate for now)

We will undoubtedly need to meet to discuss some of these points, but the hope from my end is that we can mainline the `cufinufft` stuff and mark it as `beta` reasonably quickly. This should have no impact on the existing `finufft` structure.

### CODE REVIEW

**Comment by blackwer** [comment]
@janden I made the tests more similar to `finufft`s, but with optional methods. Method `2` pretty much never works or outright crashes ("Paul's idea"). In 3d, the subproblem method fails with not having enough shared memory, and the block methods aren't accurate enough it seems. Any advice? 

```
Test project /mnt/home/rblackwell/projects/codes/finufft/build/test/cuda
    Start 25: cufinufft3d1_test_subproblem_double
1/3 Test #25: cufinufft3d1_test_subproblem_double ...***Failed    0.29 sec
[time  ] dummy warmup call to CUFFT      0.0196 s
[time  ] cufinufft plan:                 0.0195 s
[time  ] cufinufft setNUpts:             0.000121 s
error: not enough shared memory (230400)
error: cnufftspread3d_gpu_subprob
error: cuspread3d, method(2)
err: cufinufft_execute

    Start 26: cufinufft3d1_test_block_double
2/3 Test #26: cufinufft3d1_test_block_double ........***Failed    0.24 sec
[time  ] dummy warmup call to CUFFT      0.019 s
[time  ] cufinufft plan:                 0.00949 s
[time  ] cufinufft setNUpts:             0.000161 s
[time  ] cufinufft exec:                 0.00147 s
[time  ] cufinufft destroy:              0.00182 s
[Method 4] 20 NU pts to 100 U pts in 0.0129 s:  1.55e+03 NU pts/s
                                        (exec-only thoughput: 1.36e+04 NU pts/s)
[gpu   ] one mode: rel err in F[0,1,1] is 6.97e-06

    Start 28: cufinufft3d2_test_subproblem_double
3/3 Test #28: cufinufft3d2_test_subproblem_double ...***Failed    0.24 sec
[time  ] dummy warmup call to CUFFT      0.0217 s
[time  ] cufinufft plan:                 0.0184 s
[time  ] cufinufft setNUpts:             0.000142 s
error: not enough shared memory
error: cnufftspread3d_gpu_subprob
error: cuinterp3d, method(2)
err: cufinufft_execute
```

**Comment by ahbarnett** [comment]
Dear Robert & Joakim,
Great to talk yesterday.

Re advice, yes! You may enjoy reading the paper (Robert):
https://arxiv.org/abs/2102.08463
It may be worth labeling the methods consistently as in our paper: see `include/cufinufft_opts.h` which shows how SM (ie, "subproblem"), GM and GM-sort methods are selected by `gpu_method` and `gpu_sort`.
Feel free to start a better doc .rst on this. I can help edit.

a) "Paul's idea" (Paul Springer is at nVidia) was an experiment by Melody that did not end up speeding up spreading (the idea was to group together points as they were spread to reduce shared mem access). So, don't make tests for it!

b) Our paper states on p.2:
*The SM method, while providing a large acceleration for
type 1, is currently limited to single precision, due to the
small GPU shared memory per thread block (49 kB).*
Are you trying to run 3D SM in double-prec - that's a non-working combo.
Generally I think the GPU code will be most useful for single-prec.
We did do SM in 3D via 16x16x2 blocks (see Remark 1).

maxbatchsize should be put in opts, and renamed something like fft_block_size.

Here's a related question: Melody added 1d to cufinufft in 2022 (actually for Dan Foreman-Mackey + Lehman Garrison's 1D Lomb-Scargle applications in JAX) - are you bringing that in too?

Finally, the paper reminds me that we did do multi-gpu tests (on the same node)... it would be really cool to demo this again with the merged codebase.

Cheers, Alex

**Comment by blackwer** [comment]
> It may be worth labeling the methods consistently as in our paper: see `include/cufinufft_opts.h` which shows how SM (ie, "subproblem"), GM and GM-sort methods are selected by `gpu_method` and `gpu_sort`.

I relabeled all of them, though I use GM in the label, since sorting is the default and not provided as an option to the CLI interface for the tests currently. This is obviously something I can change if wanted.

> maxbatchsize should be put in opts, and renamed something like fft_block_size.

This is a breaking public API change. I'm happy to do it, since it will be consistent with the `finufft` API, but is this really OK?

> Here's a related question: Melody added 1d to cufinufft in 2022 (actually for Dan Foreman-Mackey + Lehman Garrison's 1D Lomb-Scargle applications in JAX) - are you bringing that in too?

1D is in this PR already, so good to go (it's passing tests at least :)). Let me know if I'm missing something.

> Finally, the paper reminds me that we did do multi-gpu tests (on the same node)... it would be really cool to demo this again with the merged codebase.

Agreed. I just haven't tried that functionality so I don't know how to test it properly yet.

**Comment by janden** [comment]
> a) "Paul's idea" (Paul Springer is at nVidia) was an experiment by Melody that did not end up speeding up spreading (the idea was to group together points as they were spread to reduce shared mem access). So, don't make tests for it!

I would go one step further and remove it altogether. If it's an experimental feature that doesn't deliver any improved performance, it doesn't belong in the published library. (It can still be iterated on in another branch if necessary.)

> This is a breaking public API change. I'm happy to do it, since it will be consistent with the `finufft` API, but is this really OK?

I think it's ok to break the API here, as long as we document it properly in the release notes. We're going to have to do it sooner or later, so why not now.

> Agreed. I just haven't tried that functionality so I don't know how to test it properly yet.

Yes this is probably something we should discuss separately. Currently, the code does switching between GPUs inside the cufinufft code, but this is likely not the way we want to do it – it may be more appropriate to let the user manage the GPU contexts etc. and have cufinufft be ignorant of which device it's operating on. But this is really out of my depth.

**Pull request merged**
