### PR TITLE
Remove reliance on extension modules

### PR DESCRIPTION
**Pull request by blackwer**
Following my frustrations at #389, I'm drafting this PR to just remove any extra shared library generation at install time for the python bindings. I'm basing this PR off of #393

### CODE REVIEW

**Review by janden — APPROVED** [review]
This looks good. Just feels a bit strange to include shared libraries as “data” files but seems to work.

Should we give finufft the same treatment, then?

**Comment by blackwer** [comment]
already done in this PR

**Comment by janden** [comment]
> already done in this PR

Weird. Somehow missed it. Anyhow saw it now and it looks good.

Tried making the binary wheels using the docker image for cufinufft. Everything looks good there too. One interesting consequence is that we're now independent of the CPython ABI(?). In other words, we only need to ship a single binary wheel `cufinufft-2.2.0.dev0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl`. So that's a +1 for ctypes!

**Comment by blackwer** [comment]
you were blinded by all of my shiny force pushes

**Comment by blackwer** [comment]
This still needs a bit of hardening for macs. In some instances macs get a `dylib` and others a `so`. Can't rely solely on the platform.

**Comment by janden** [comment]
Maybe related, but the wheel names are the same (`finufft-2.2.0.dev0-py3-none-any.whl`) for both win and mac, which I assume would cause problems.

**Comment by lu1and10** [comment]
> Maybe related, but the wheel names are the same (`finufft-2.2.0.dev0-py3-none-any.whl`) for both win and mac, which I assume would cause problems.

The python version is not encoded in name either. The master branch ci generates 
finufft-2.2.0.dev0-cp36-cp36m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
finufft-2.2.0.dev0-cp38-cp38m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
etc
after changing, it generates finufft-2.2.0.dev0-py3-none-any.whl for all python versions.
https://github.com/flatironinstitute/finufft/actions/runs/7185113178/job/19567673308#step:6:407
Not sure how to fix.

**Comment by lu1and10** [comment]
> > Maybe related, but the wheel names are the same (`finufft-2.2.0.dev0-py3-none-any.whl`) for both win and mac, which I assume would cause problems.
> 
> The python version is not encoded in name either. The master branch ci generates finufft-2.2.0.dev0-cp36-cp36m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl finufft-2.2.0.dev0-cp38-cp38m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl etc after changing, it generates finufft-2.2.0.dev0-py3-none-any.whl for all python versions. https://github.com/flatironinstitute/finufft/actions/runs/7185113178/job/19567673308#step:6:407 Not sure how to fix.

maybe it's fine, building extension module is python version dependent while ship with .so as data does not require python version?

**Comment by janden** [comment]
> maybe it's fine, building extension module is python version dependent while ship with .so as data does not require python version?

Right. Since we don't depend on the Python ABI, it makes sense that the wheel should be independent of Python version.



> the .so, .dylib or .dll file may be os dependent, maybe there is a way to tell `package_data`, it's os dependent so the wheel name will be named accordingly..

Yes this is an issue. Right now, Linux has a different tag (`manylinux`) but macOS and Windows have the same names.

**Comment by janden** [comment]
I'm a little worried this may introduce new bugs that we don't completely have a handle on relatively close to a release. At the end of the day, the old way (C extension with rpath and friends) works except for certain corner cases and we expect most people to install the binary wheels anyhow where this wouldn't be an issue. Besides, wouldn't some of these issues (compiler incompatibility, etc.) be resolved once we move to scikit-build (integrating the library building inside the pip install process)?

**Comment by blackwer** [comment]
> I'm a little worried this may introduce new bugs that we don't completely have a handle on relatively close to a release. At the end of the day, the old way (C extension with rpath and friends) works except for certain corner cases and we expect most people to install the binary wheels anyhow where this wouldn't be an issue. Besides, wouldn't some of these issues (compiler incompatibility, etc.) be resolved once we move to scikit-build (integrating the library building inside the pip install process)?

I'm not sure I'd recommend `scikit-build` here necessarily. This solution is showing a fair amount of benefits so far. We also don't need to merge it before release. I was having issues with the ubuntu cython fix, so I opted to try a different method as a trial to completely circumvent it. Currently this PR is more of a playground, but I'm relatively confident as of right now it's a good long-term solution.

That said, I think I can get a handle on the bugs (I can actually test the binaries on a lot of platforms directly). If the wheels work, which is what this is mostly designed to deal with, then I don't see much of an issue with merging it.

**Comment by ahbarnett** [comment]
This will get taken care of by #429

**Comment by ahbarnett** [comment]
closing this 2023 PR since superceded by #429 @janden @blackwer @lu1and10 @DiamonDinoia

**Pull request closed without merging**
