### PR TITLE
Make the time interface windows compatible

### PR DESCRIPTION
**Pull request by DiamonDinoia**
Hi all,

The time interface was using linux specific API that did not work on windows.
I replaced it using chrono since it is portable. Chrono accuracy is implementation dependent so if we want the highest accuracy we should query the performance counters on windows.

Now it is possible to build finufft with cmake on windows without minGW or similars.

Thanks,
Marco

### CODE REVIEW

**Comment by lu1and10** [comment]
Hi Marco,

Thanks for the PR! I'm curious about "build finufft with cmake on windows without minGW or similars." Does it mean that you can build with Microsoft Visual C++? One still needs one compiler. 

Best,
Libin

**Comment by DiamonDinoia** [comment]
Thanks for pointing that out. It works on bare metal windows MSVC or clang.

**Review by ahbarnett — APPROVED** [review]
ok, cmake linux ubuntu build works my end. CI works. I'll bring it in.

**Comment by ahbarnett** [comment]
Thanks for this!

**Pull request merged**
