### PR TITLE
cmake: Add install targets for (cu)finufft

### PR DESCRIPTION
**Pull request by blackwer**
Does what it says. Open questions:

- should we add examples to `${INSTALL_PREFIX}/share/finufft`
- should we bother with other language bindings? I currently ignore fortran headers/mod files, since there isn't a standard for where to put those (at least the mod file). In the past I put them in `${INSTALL_PREFIX}/share/myproject/fortran` or something similar. We should definitely not deal with `python` here imo.

### CODE REVIEW

**Comment by ahbarnett** [comment]
Thanks! I referred to it in the XSDK Issue. However, their description includes: 

_M13. When configured with a prefix, a package must install its headers and libraries under <install-prefix>/include/ and <install-prefix>/[lib,lib64]/, respectively._ 

How does this jibe w/ typical cmake repo layout? (it may not, and we have to make a decision..)

Also as a new cmake user, I don't know the command (cmake install?)
Could you add to the CMake part of docs/install.rst how to perform this installation and how the library user should link to the resulting .so or .a ? Or we can discuss, and we can write it together.

[now I have to sort out the related rpath issue for telling users how to link against the .so ...]

**Comment by blackwer** [comment]
Alex, I've updated the docs to have a `cmake` install/`rpath` example. I also moved `finufft_eitherprec.h` up one directory, since it's technically a public header, even if users shouldn't include it directly. This simplified the install code (well, fixed it, but I could have worked around...)

**Review by ahbarnett — APPROVED** [review]
works my end.
Questions:
1) why would `lib64` arise (is that set by GNUInstallDirs ?)
2) I see the default value of CMAKE_INSTALL_PREFIX is /usr/local/  for me - which users don't have write perms for - is that fine to leave? (maybe a note in docs?)
3) we should think about CMakePresets.json for the standard OSX and Windows installs (it appears the PREFIX has a sensible default due to CMake on various OSes?)

**Comment by ahbarnett** [comment]
I forgot to say thanks and respond to your qu's at the top of the PR:
* yes re copy examples to share/finufft/    The fortran examples (if built) could go to share/finufft/fortran as you say.
* no, agree leave the other language bindings. 

There are many other issues I'm confused about re cmake, eg, should gpu-examples be a separate build target? Can we set up an OCTAVE interface target? The interaction with python is minimal. Is it possible to have test-matlab, test-octave targets? We should chat about this design stuff some time...

**Review by lu1and10 — APPROVED** [review]
It works on my end too.

**Comment by blackwer** [comment]
> why would `lib64` arise (is that set by GNUInstallDirs ?)

It depends on your system and I don't have a concrete answer. Sometimes they're just symlinked to each other so they're equivalent, but it will conform as best as possible to https://www.gnu.org/prep/standards/html_node/Directory-Variables.html

https://unix.stackexchange.com/questions/74646/difference-between-lib-lib32-lib64-libx32-and-libexec also has some nice discussion

> I see the default value of CMAKE_INSTALL_PREFIX is /usr/local/ for me - which users don't have write perms for - is that fine to leave? (maybe a note in docs?)

I think it's fine to leave -- it's standard for both cmake and autotools and probably other build utilities. A note in the docs might be helpful, so I'll add that

> we should think about CMakePresets.json for the standard OSX and Windows installs (it appears the PREFIX has a sensible default due to CMake on various OSes?)

I don't even know what PREFIX would be on windows or what that means. Installs of shared libraries on windows aren't really a thing in general (you used to just dump things in `c:/windows/system32` I guess. I'm not even sure they allow that anymore) -- most things just build a `dll` and leave it in the project root or link statically/build directly into the project. 

It's almost certainly `/usr/local` on OS X.

> yes re copy examples to share/finufft/ The fortran examples (if built) could go to share/finufft/fortran as you say.

will do

> There are many other issues I'm confused about re cmake, eg, should gpu-examples be a separate build target? Can we set up an OCTAVE interface target? The interaction with python is minimal. Is it possible to have test-matlab, test-octave targets? We should chat about this design stuff some time...

Yeah let's discuss this stuff offline.

**Pull request merged**
