### PR TITLE
Add unit tests for Python interface

### PR DESCRIPTION
**Pull request by janden**
Since the Python compatibility layer is quite big (about 1000 lines), it would be good to have unit tests to make sure that everything works correctly, including proper handling of arrays and dtypes.

### CODE REVIEW

**Comment by janden** [comment]
So this is ready now. These unit tests cover about 98% of the lines in the Python layer. You can run it locally using:
```bash
pip install pytest
pytest python/finufft/test
```

The untested lines are either fatal errors (like not being able to load the dynamic library in `_finufft.py`) or error handling for `execute` and `destroy` which either can't error (`execute`) or don't error under the current setup (`destroy` will only error if you give it a NULL pointer, which we do not). Still, it's better to keep these lines in since that behavior may change in the future.

The only other line I wasn't able to test is this one: https://github.com/flatironinstitute/finufft/blob/0e5f3f3b3ec07ac8b7e7ccd26d88d2c912c1b9a6/python/finufft/finufft/_interfaces.py#L336
Maybe @lu1and10 can shed some light on when it's triggered?

**Comment by ahbarnett** [comment]
The `_copy` method seems to be used only when writing into an existing output array, which already has been tested to the be correct shape. I recall this was some quite subtle thing, like it still being F vs C ordered, needing a transpose, or something. I feel like Joakim, Libin, and David Stein went back and forth a while on this in around 2021?

**Comment by janden** [comment]
1. So the way I compiled and installed was the following
```
make -p build
cd build
cmake ..
make -j
cd ..
pip install -e python/finufft
```

Then I run `pytest python/finufft/test` and everything passes. From what I understand, `make python` essentially does this last line (`pip install -e python/finufft`), so that makes sense.

2. When you run `pip install finufft`, `pip` will look online (on PyPI) for the latest published version of finufft (which is 2.1.0) and conclude that you already have a newer version installed (the one from step 1) and do nothing. When you run `pytest python/finufft/test`, it's using the same code as in step 1. The reason the test may be failing is that the type 3 tolerance is too tight (I used `50 * tol` locally and it worked, but on the CI machines, I had to increase it to `60 * tol`, but maybe that's too tight still).

3. Yeah that's strange. Running the tests on the old version (2.1.0) does not give me that error but passes all the tests except for one (`test_finufft_plan_errors`) which I think is due to how the error message has changed since 2.1.0. In a fresh venv, I just ran

```
pip install finufft
pytest python/finufft/test
```

**Comment by lu1and10** [comment]
> So this is ready now. These unit tests cover about 98% of the lines in the Python layer. You can run it locally using:
> 
> ```shell
> pip install pytest
> pytest python/finufft/test
> ```
> 
> The untested lines are either fatal errors (like not being able to load the dynamic library in `_finufft.py`) or error handling for `execute` and `destroy` which either can't error (`execute`) or don't error under the current setup (`destroy` will only error if you give it a NULL pointer, which we do not). Still, it's better to keep these lines in since that behavior may change in the future.
> 
> The only other line I wasn't able to test is this one:
> 
> https://github.com/flatironinstitute/finufft/blob/0e5f3f3b3ec07ac8b7e7ccd26d88d2c912c1b9a6/python/finufft/finufft/_interfaces.py#L336
> 
> Maybe @lu1and10 can shed some light on when it's triggered?

It seems the _copy function is only applied to `_out` and `out` in the `execute` function, and it's not triggered because the logic in `_ensury_array_type` is: if `out` is None, we make a new `_out` memory; if `out` is not None, `_out` has to be the same as `out` or error exception(`out` does not have correct proprieties).

The old _*chk* functions was replaced in this commit [](https://github.com/flatironinstitute/finufft/commit/2026c7e59472c92699b4073566baf752abd6ee9d). The old _chk made a new `_out` memory if `out` is not None and does not have correct properties instead of giving an error.

With current `_ensury_array_type`, I guess we are good to remove `_copy` function since we are stricter on checking `out` argument in the `execute` function.

**Comment by lu1and10** [comment]
> So this is ready now. These unit tests cover about 98% of the lines in the Python layer. You can run it locally using:
> 
> ```shell
> pip install pytest
> pytest python/finufft/test
> ```
> 
> The untested lines are either fatal errors (like not being able to load the dynamic library in `_finufft.py`) or error handling for `execute` and `destroy` which either can't error (`execute`) or don't error under the current setup (`destroy` will only error if you give it a NULL pointer, which we do not). Still, it's better to keep these lines in since that behavior may change in the future.
> 
> The only other line I wasn't able to test is this one:
> 
> https://github.com/flatironinstitute/finufft/blob/0e5f3f3b3ec07ac8b7e7ccd26d88d2c912c1b9a6/python/finufft/finufft/_interfaces.py#L336
> 
> Maybe @lu1and10 can shed some light on when it's triggered?

One minor point, with current `_ensury_array_type` logic, `data` argument in `execute` can be np array slicing, while `out` argument can not be np array slicing.

**Comment by janden** [comment]
> With current `_ensury_array_type`, I guess we are good to remove `_copy` function since we are stricter on checking `out` argument in the `execute` function.

Thanks for the explanation! Will remove it then.

> One minor point, with current `_ensury_array_type` logic, `data` argument in `execute` can be np array slicing, while `out` argument can not be np array slicing.

Just to make sure I understand, you're saying that `data` does not need to be contiguous (i.e., we can take `data = x[::2]` and it'll still work)? That sounds about right. We'll just perform a copy in that case.

> For 1,2, I'm able to make the test pass with large type 3 tolerance as Joakim does. For 3, I also passed all the tests...

Cool. I guess I need to increase the tolerance for type 3 then (maybe `100 * tol` to be safe). As a sidenote, is there a good reason why type 3 is much worse in terms of accuracy here?

> I have tested with skbuild using cmake to build finufft python wrappers locally, I should be able to make a PR for that.

That would be amazing. If we have skbuild working, we can even publish a source package and have users compile on their own if needed, if I understand things correctly.

**Comment by lu1and10** [comment]
> Just to make sure I understand, you're saying that `data` does not need to be contiguous (i.e., we can take `data = x[::2]` and it'll still work)? That sounds about right. We'll just perform a copy in that case.

Yes, I think these lines make a copy for `data` [https://github.com/flatironinstitute/finufft/blob/4d3b2e5995f47fa96b34b01564a419dc0f50083d/python/finufft/finufft/_interfaces.py#L319-L325](https://github.com/flatironinstitute/finufft/blob/4d3b2e5995f47fa96b34b01564a419dc0f50083d/python/finufft/finufft/_interfaces.py#L319-L325) if the `data` is not continuous, for `out` it just output an error message.

**Comment by janden** [comment]
> Yes, I think these lines make a copy for `data`

Right. Yeah that's all as it should be then. I think we test for it and make sure the warning is emitted properly.

**Comment by ahbarnett** [comment]
Ok, great. The tests as you have them indeed work.
I filed an issue to make the docs match this procedure.

I'll wait for you (Libin and Joakim) to remove the _copy code logic, and update 60*tol to 100*tol.
(It looks like you're fixing rand seeds at 0, right? so it should be nonstochastic).
Small t3 transforms can have up to 2 digits worse than tol.
The whole error model is stochastic anyway (see paper).

Then we can bring in. Thanks, Alex

**Comment by janden** [comment]
> I'll wait for you (Libin and Joakim) to remove the _copy code logic, and update 60_tol to 100_tol.

Done and done.

> (It looks like you're fixing rand seeds at 0, right? so it should be nonstochastic).

Yes but there still seems to be some variability between computers. Like I said, the tests pass on my laptop with `50 * tol`, but on the CI, it seems to need `60 * tol` while your computer gives a different result. So there's still some stohasticity here that I can't quite nail down.

> Small t3 transforms can have up to 2 digits worse than tol.

Ok that's what I figured.

**Pull request merged**
