### PR TITLE
avoid 'inv' array in bin_sort

### PR DESCRIPTION
**Pull request by mreineck**
Unless I'm missing something, it should be possible to perform the bin sorting without the additional `inv` vector. The resulting code is shorter and should also be faster, since it avoids the writing and subsequent reading of `inv`, and the times for random memory accesses may be partially overlapped with the bin index computations.
I didn't do any benchmarking however ...

### CODE REVIEW

**Comment by mreineck** [comment]
I don't understand the Windows CI failure; perhaps it's unrelated?

**Comment by ahbarnett** [comment]
Some tests on Ryzen 7 5700U laptop (8 cores). One easy sorting-dominated test is to go to 1D, low acc, large N.
By default dir=2 (interp) has sorting switched off, so we're only looking at the dir=1 times:
```
perftest/spreadtestnd 1 1e8 1e8 1e-1
nthreads      1     4   8   16 (full HT)
master         13.7s  4.6s   3.5s  6.6s        (notice slow-down with full HT)
PR#291       14s     4.3s    3.0s   3.6s
```
So, improvement at large thread count (esp 80% faster at full HT); no improvement for single-thread.
Now for single-prec:
```
perftest/spreadtestndf 1 1e8 1e8 1e-1
nthreads      1     4   8   16 (full HT)
master         10.7s  3.7s   3.5s  6.1s        (notice slow-down with full HT)
PR#291       10.6s     3.4s    2.4s   3.0s    (only slight slow-down with HT)
```
similar story. Very nice.

**Comment by ahbarnett** [comment]
We test xeon 16-core 6244 gold. Same test as for laptop above.
```
perftest/spreadtestnd 1 1e8 1e8 1e-1
nthreads      1    16      32 (full HT)
master:      9.8s   3.4s   4.9s
PR#291:     9.9s    2.15s  4.7s
```
We see >50% speedup at 1thread/core, but both suffer badly with full HT.
```
perftest/spreadtestndf 1 1e8 1e8 1e-1
nthreads       1    16    32
master:       9.6s   3.25s  4.5s
PR#291:      9.5s   2.12s  4.4s
```
Similar story to double prec.   THe advantage peaks at +50% efficiency at 1 thread/core.

**Comment by ahbarnett** [comment]
I am also seeing 20% speedups in 3D spreading on the xeon @ 1 thread/core, and 5-8% at OMP_NUM_THREADS=4.

**Pull request merged**
